-- MySQL Script generated by MySQL Workbench
-- mar. 26 mars 2019 18:38:20 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema private_shop_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `private_shop_db` ;

-- -----------------------------------------------------
-- Schema private_shop_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `private_shop_db` DEFAULT CHARACTER SET utf8 ;
USE `private_shop_db` ;

-- -----------------------------------------------------
-- Table `private_shop_db`.`t_shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `private_shop_db`.`t_shops` (
  `id_shop` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `mail` LONGTEXT NOT NULL,
  `tel_number` VARCHAR(45) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `country` VARCHAR(255) NOT NULL,
  `post_code` VARCHAR(255) NOT NULL,
  `description` LONGTEXT NULL,
  `picture` VARCHAR(45) NULL,
  PRIMARY KEY (`id_shop`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `private_shop_db`.`t_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `private_shop_db`.`t_products` (
  `id_product` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `t_shops_id_shop` INT NOT NULL,
  PRIMARY KEY (`id_product`),
  INDEX `fk_t_products_t_shops_idx` (`t_shops_id_shop` ASC),
  CONSTRAINT `fk_t_products_t_shops`
    FOREIGN KEY (`t_shops_id_shop`)
    REFERENCES `private_shop_db`.`t_shops` (`id_shop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `private_shop_db`.`t_details_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `private_shop_db`.`t_details_product` (
  `id_details_product` INT NOT NULL,
  `quantity` INT NOT NULL,
  `description` LONGTEXT NOT NULL,
  `sales` INT NOT NULL,
  `price` INT NOT NULL,
  `t_products_id_product` INT NOT NULL,
  PRIMARY KEY (`id_details_product`),
  INDEX `fk_t_details_product_t_products1_idx` (`t_products_id_product` ASC),
  CONSTRAINT `fk_t_details_product_t_products1`
    FOREIGN KEY (`t_products_id_product`)
    REFERENCES `private_shop_db`.`t_products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `private_shop_db`.`t_customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `private_shop_db`.`t_customers` (
  `id_customers` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `tel_number` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `post_code` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_customers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `private_shop_db`.`t_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `private_shop_db`.`t_category` (
  `id_category` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `private_shop_db`.`t_products_has _t_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `private_shop_db`.`t_products_has _t_category` (
  `t_products_id_product` INT NOT NULL,
  `t_category_id_category` INT NOT NULL,
  PRIMARY KEY (`t_products_id_product`, `t_category_id_category`),
  INDEX `fk_t_products_has_t_category_t_category1_idx` (`t_category_id_category` ASC),
  INDEX `fk_t_products_has_t_category_t_products1_idx` (`t_products_id_product` ASC),
  CONSTRAINT `fk_t_products_has_t_category_t_products1`
    FOREIGN KEY (`t_products_id_product`)
    REFERENCES `private_shop_db`.`t_products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_products_has_t_category_t_category1`
    FOREIGN KEY (`t_category_id_category`)
    REFERENCES `private_shop_db`.`t_category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `private_shop_db`.`t_sizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `private_shop_db`.`t_sizes` (
  `id_sizes` INT NULL,
  `size` VARCHAR(25) NULL,
  PRIMARY KEY (`id_sizes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `private_shop_db`.`t_products_has_t_sizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `private_shop_db`.`t_products_has_t_sizes` (
  `t_products_id_product` INT NOT NULL,
  `t_sizes_id_sizes` INT NOT NULL,
  PRIMARY KEY (`t_products_id_product`, `t_sizes_id_sizes`),
  INDEX `fk_t_products_has_t_sizes_t_sizes1_idx` (`t_sizes_id_sizes` ASC),
  INDEX `fk_t_products_has_t_sizes_t_products1_idx` (`t_products_id_product` ASC),
  CONSTRAINT `fk_t_products_has_t_sizes_t_products1`
    FOREIGN KEY (`t_products_id_product`)
    REFERENCES `private_shop_db`.`t_products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_products_has_t_sizes_t_sizes1`
    FOREIGN KEY (`t_sizes_id_sizes`)
    REFERENCES `private_shop_db`.`t_sizes` (`id_sizes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `private_shop_db`.`t_colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `private_shop_db`.`t_colors` (
  `id_colors` INT NOT NULL,
  `colors` VARCHAR(45) NULL,
  PRIMARY KEY (`id_colors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `private_shop_db`.`t_products_has_t_colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `private_shop_db`.`t_products_has_t_colors` (
  `t_products_id_product` INT NOT NULL,
  `t_colors_id_colors` INT NOT NULL,
  PRIMARY KEY (`t_products_id_product`, `t_colors_id_colors`),
  INDEX `fk_t_products_has_t_colors_t_colors1_idx` (`t_colors_id_colors` ASC),
  INDEX `fk_t_products_has_t_colors_t_products1_idx` (`t_products_id_product` ASC),
  CONSTRAINT `fk_t_products_has_t_colors_t_products1`
    FOREIGN KEY (`t_products_id_product`)
    REFERENCES `private_shop_db`.`t_products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_products_has_t_colors_t_colors1`
    FOREIGN KEY (`t_colors_id_colors`)
    REFERENCES `private_shop_db`.`t_colors` (`id_colors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `private_shop_db`.`t_baskets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `private_shop_db`.`t_baskets` (
  `id_basket` INT NOT NULL,
  `t_customers_id_customers` INT NOT NULL,
  PRIMARY KEY (`id_basket`),
  INDEX `fk_t_baskets_t_customers1_idx` (`t_customers_id_customers` ASC),
  CONSTRAINT `fk_t_baskets_t_customers1`
    FOREIGN KEY (`t_customers_id_customers`)
    REFERENCES `private_shop_db`.`t_customers` (`id_customers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `private_shop_db`.`t_baskets_has_t_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `private_shop_db`.`t_baskets_has_t_products` (
  `t_baskets_id_basket` INT NOT NULL,
  `t_products_id_product` INT NOT NULL,
  PRIMARY KEY (`t_baskets_id_basket`, `t_products_id_product`),
  INDEX `fk_t_baskets_has_t_products_t_products1_idx` (`t_products_id_product` ASC),
  INDEX `fk_t_baskets_has_t_products_t_baskets1_idx` (`t_baskets_id_basket` ASC),
  CONSTRAINT `fk_t_baskets_has_t_products_t_baskets1`
    FOREIGN KEY (`t_baskets_id_basket`)
    REFERENCES `private_shop_db`.`t_baskets` (`id_basket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_baskets_has_t_products_t_products1`
    FOREIGN KEY (`t_products_id_product`)
    REFERENCES `private_shop_db`.`t_products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
